# Generated by Django 2.0.3 on 2018-07-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180708_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_created', to='api.UserInfo'),
        ),
    ]
