# Generated by Django 2.0.7 on 2018-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180708_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='api.Tag'),
        ),
    ]
