# Generated by Django 2.0.7 on 2018-07-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180709_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user_info',
        ),
    ]
