# Generated by Django 2.0.7 on 2018-07-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180709_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_info',
            new_name='userinfo',
        ),
    ]
