# Generated by Django 2.0.7 on 2018-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180709_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='like_count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='comment_like',
            field=models.ManyToManyField(related_name='comment_like', to='api.Comment'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='recipe_like',
            field=models.ManyToManyField(related_name='recipe_like', to='api.Recipe'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='recipe_collection',
            field=models.ManyToManyField(related_name='recipe_collection', to='api.Recipe'),
        ),
    ]
