# Generated by Django 2.0.7 on 2018-07-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180710_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='like_count',
        ),
    ]
